### PR TITLE
fix:freeCodeCamp/freeCodeCamp#47257

### PR DESCRIPTION
**Pull request by xinwei47**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

closes freeCodeCamp/freeCodeCamp/issues/47257

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Thanks for looking into the issue. Your proposed solution does not seem to resolve the issue. I was wondering if it is working on your side?

**Comment by xinwei47** [comment]
Yes, I followed the instructions on discourse to test the change. The anchor link headings were not hidden by the nav on my machine. Can you please advise if I miss anything or any additional testing I should do? Thank you.

**Comment by xinwei47** [comment]
@ahmadabdolsaheb I just retested the changes using discourse theme creator and theme CLI and looks like they work. Let me know if there is anything else I can do to make this work.

By the way, I also rewrote the code using $--global-nav-height. But for some reasons, syntax like #{$--global-nav-height} + 1em didn't work.

**Comment by xinwei47** [comment]
@ahmadabdolsaheb Same logic, but rewrote it using --global-nav-height. Also retested the changes using discourse CLI and theme creator, everything works on my end. Please advise if there is anything else I can do to make this work. Thank you.

**Comment by ahmadabdolsaheb** [comment]
This should work. Since the navigation's height doubles on small screens, I would appreciate it if you could make the necessary adjustment in a media query.

**Comment by xinwei47** [comment]
@ahmadabdolsaheb Added media query. Please let me know if it works on your side. Thank you.

Just a little thought on the media queries, may be helpful to create global variables for different breakpoints which will be easier to manage.

**Comment by ahmadabdolsaheb** [comment]
Thanks for making the adjustments. This pr should be good to go.

> Just a little thought on the media queries, may be helpful to create global variables for different breakpoints which will be easier to manage.

That is a good idea. If you are interested in turning to the breakpoints into variables, feel free to create a pr and tag me.

**Review by ahmadabdolsaheb — APPROVED** [review]

**Comment by xinwei47** [comment]
@ahmadabdolsaheb I would like to get your thoughts before making commits to the breakpoints. Please let me know if you would like to create another issue for this topic. 

Below are the current media queries breakpoints that I found in the common.scss:
```
max-width: 400px
min-width: 500px
min-width: 800px
max-width: 850px
min-width: 851px
min-width: 1020px
min-width: 1200px
```
One option is to create global sass variables which are listed as below: 
```
$screen-xxs-max: 400px;
$screen-xs-min: 401px;
$screen-xs-max: 499px;
$screen-sm-min: 500px;
$screen-sm-max: 799px;
$screen-md-min: 800px;
$screen-md-max: 850px;
$screen-lg-min: 851px;
$screen-lg-max: 1019px;
$screen-xl-min: 1020px;
$screen-xl-max: 1199px;
$screen-xxl-min: 1200px;
```
The method above is pretty straightforward, but I found another cleaner option which is to write a mixin to manage breakpoints to get the rid of typing min-width and max-width, like this article shows: https://www.sitepoint.com/managing-responsive-breakpoints-sass/#with-a-configurable-mixin. 

Please let me know your thoughts on which method we should adopt to manage the breakpoints so it can better fit into our future needs effectively as the platform grow.

**Comment by ahmadabdolsaheb** [comment]
@xinwei47, thanks for looking into this. Yes using mixins would be a good idea.

**Pull request merged**
