### PR TITLE
Update scss

### LINKED ISSUE #136: Using core SCSS color variables in themes is deprecated
As far as I can tell, there seems to be an issue with the themes we're using in the SCSS files. I would love to update and fix it.

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #136

I also updated the spelling on some of the classes we were using. 

Let me know if it's okay to delete some of the old SCSS variables. I think I managed to get all of them that mattered.

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
image

I ran this through the Discourse theme testing instance. It looks like we're not actually using the `color_definitions.scss` file?

**Comment by a2937** [comment]
That's certainly odd. I'll double check the documentation.

**Comment by a2937** [comment]
Okay I fixed one error message. Time to fix the other one.

**Comment by a2937** [comment]
```Error: $color2: fcc-highlight-lightness-switch(#0088cc) is not a color. ╷ 14 │ $fcc-highlight-mid: mix($fcc-highlight-color, $fcc-highlight-background, 50%); │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ╵ /var/www/discourse/common.scss 14:21 root stylesheet``` 

I think I only have a SCSS problem left.

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
