### PR TITLE
feat: add july  footer

### PR DESCRIPTION
**Pull request by ahmadabdolsaheb**

### CODE REVIEW

**Comment by Nirajn2311** [comment]
Is there a way to automate the creation of this PR or the updation of the footer as it seems kinda redundant doing it manually. Also how are you getting the list of articles? Are they the most read articles of that month or the articles which were released in that month?

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Comment by scissorsneedfoodtoo** [comment]
Hey @Nirajn2311, those are all great points you bring up.

There probably is a better way of updating the footer, though I personally haven't put much thought into it.

We only update the footer once every quarter or so, and Quincy and Abbey choose the English articles. For the other languages, Miya and Rafael decide on those. Either they use translated versions of the articles Quincy and Abbey chose, or use other articles that they want to promote on either publication.

**Comment by Nirajn2311** [comment]
I see, then I doubt it can be automated as you'll need the list beforehand to do it. But if the list were to be taken from say google analytics then maybe it could've been automated.

**Pull request merged**
