### PR TITLE
Update footer Apr 2022

### PR DESCRIPTION
**Pull request by ahmadabdolsaheb**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

Steps to review: 
1) From the hamburger menu on the forum go to `Admin` and then `Customize` -> `Themes` and click on `Install`.
Screen Shot 2022-04-07 at 3 20 08 PM

2) Click on `From a git repository`, enter the repository containing theme. Then click on Advanced and enter the branch name. Next press 'Install'.

Note: If you are prompted about having a theme with the same name, press on `yes`.

Screen Shot 2022-04-07 at 3 21 50 PM

3) While having the newly added theme selected, scroll to the bottom of the page and click on `preview` to see the forum using the newly installed theme.

Screen Shot 2022-04-07 at 3 40 09 PM

4) Finally, review if the intended pull request changes has taken place and submit your review.

Here is the new footer on test theme on the forum for your review: https://forum.freecodecamp.org/admin/customize/themes/59

### CODE REVIEW

**Review by nhcarrigan — COMMENTED** [review]
That preview link is incredibly helpful.

Just to clarify, this is intentionally different from the `/learn` updates right?

**Comment by ahmadabdolsaheb** [comment]
They should be the same :)

**Review by nhcarrigan — APPROVED** [review]
They are the same, after looking at the learn footer properly. 😁

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Pull request merged**
